version: 2
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/webpack-blocks-copy
    steps:
      - checkout
      - restore_cache:
          key: webpack-blocks-copy-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: webpack-blocks-copy-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: yarn test
